# Generated by Django 5.2.12 on 2026-03-06 08:27

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('color', models.CharField(blank=True, max_length=32)),
                ('is_system', models.BooleanField(default=False)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=16)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=16)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('by_month_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_on'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subcategory', models.CharField(blank=True, max_length=120)),
                ('payment_method', models.CharField(blank=True, max_length=64)),
                ('income_type', models.CharField(blank=True, max_length=64)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('color', models.CharField(blank=True, max_length=32)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('template_type', models.CharField(choices=[('normal', 'Normal'), ('fixed_expense', 'Fixed expense'), ('fixed_income', 'Fixed income'), ('loan', 'Loan'), ('installment_purchase', 'Installment purchase'), ('credit_card_payment', 'Credit card payment'), ('vehicle_expense', 'Vehicle expense')], default='normal', max_length=32)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'kind', 'ordering'], name='finance_cat_user_id_e77cb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'kind', 'name', 'parent'), name='uniq_category_per_user'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['user', 'kind', 'template_type'], name='finance_tem_user_id_c5952c_idx'),
        ),
    ]
