# Generated by Django 5.2.12 on 2026-03-06 08:27

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixed_rules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('income_type', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('expected', 'Expected'), ('received', 'Received'), ('missed', 'Missed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='expected', max_length=16)),
                ('expected_on', models.DateField()),
                ('received_on', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('is_guaranteed', models.BooleanField(default=False)),
                ('source_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_entries', to='fixed_rules.fixedincomerule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expected_on', '-created_at'],
                'indexes': [models.Index(fields=['user', 'expected_on'], name='income_inco_user_id_8c529f_idx'), models.Index(fields=['user', 'status', 'received_on'], name='income_inco_user_id_9a36e9_idx')],
            },
        ),
    ]
