# Generated by Django 5.2.12 on 2026-03-06 08:27

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supabase_user_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('onboarding_state', models.CharField(choices=[('new', 'New'), ('profile_completed', 'Profile completed'), ('active', 'Active')], default='new', max_length=32)),
                ('opening_balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('opening_balance_date', models.DateField(blank=True, null=True)),
                ('income_projection_mode', models.CharField(choices=[('expected', 'Expected'), ('received_only', 'Received only')], default='expected', max_length=32)),
                ('mandatory_category_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
