# Generated by Django 5.2.12 on 2026-03-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleexpense',
            name='linked_expense',
        ),
    ]
