# Generated by Django 5.2.12 on 2026-03-06 08:27

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('lender', models.CharField(blank=True, max_length=255)),
                ('principal_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('repayment_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest_total', models.DecimalField(decimal_places=2, default='0.00', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fee_total', models.DecimalField(decimal_places=2, default='0.00', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('installment_count', models.PositiveIntegerField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_day', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('first_installment_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid_off', 'Paid off'), ('restructured', 'Restructured'), ('defaulted', 'Defaulted')], default='active', max_length=24)),
                ('note', models.TextField(blank=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_on', models.DateField()),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('principal_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fee_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'status', 'start_date'], name='loans_loan_user_id_dbd84c_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['user', 'due_on', 'status'], name='loans_loani_user_id_2c136a_idx'),
        ),
        migrations.AddConstraint(
            model_name='loaninstallment',
            constraint=models.UniqueConstraint(fields=('loan', 'installment_number'), name='uniq_loan_installment_number'),
        ),
    ]
