# Generated by Django 5.2.12 on 2026-03-06 08:27

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('issuer', models.CharField(blank=True, max_length=120)),
                ('last4', models.CharField(blank=True, max_length=4)),
                ('statement_due_day', models.PositiveSmallIntegerField()),
                ('statement_close_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('principal_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fee_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_on', models.DateField()),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='planned', max_length=16)),
                ('minimum_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('note', models.TextField(blank=True)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credit_cards.creditcardaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_on'],
            },
        ),
        migrations.AddIndex(
            model_name='creditcardaccount',
            index=models.Index(fields=['user', 'is_active'], name='credit_card_user_id_9a5539_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcardpayment',
            index=models.Index(fields=['user', 'status', 'due_on'], name='credit_card_user_id_1cd532_idx'),
        ),
    ]
