# Generated by Django 5.2.12 on 2026-03-06 08:27

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit_cards', '0001_initial'),
        ('finance', '0001_initial'),
        ('fixed_rules', '0001_initial'),
        ('installments', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('title', models.CharField(max_length=255)),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('principal_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fee_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subcategory', models.CharField(blank=True, max_length=120)),
                ('payment_method', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='planned', max_length=16)),
                ('entry_type', models.CharField(choices=[('one_time', 'One time'), ('recurring', 'Recurring'), ('fixed', 'Fixed'), ('installment', 'Installment'), ('loan_payment', 'Loan payment'), ('credit_card_payment', 'Credit card payment'), ('vehicle', 'Vehicle')], default='one_time', max_length=32)),
                ('incurred_on', models.DateField()),
                ('due_on', models.DateField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='finance.category')),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='credit_cards.creditcardaccount')),
                ('installment_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='installments.installmentpurchase')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='loans.loan')),
                ('source_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_entries', to='fixed_rules.fixedexpenserule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-incurred_on', '-created_at'],
            },
        ),
    ]
