# Generated by Django 5.2.12 on 2026-03-06 08:27

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='vehicles.vehicle'),
        ),
        migrations.AddIndex(
            model_name='expenseentry',
            index=models.Index(fields=['user', 'incurred_on'], name='expenses_ex_user_id_0dbb56_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseentry',
            index=models.Index(fields=['user', 'status', 'due_on'], name='expenses_ex_user_id_a0fe3e_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseentry',
            index=models.Index(fields=['user', 'entry_type'], name='expenses_ex_user_id_99106a_idx'),
        ),
        migrations.AddConstraint(
            model_name='expenseentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount_total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('principal_amount'), '+', models.F('interest_amount')), '+', models.F('fee_amount'))), models.Q(('fee_amount', 0), ('interest_amount', 0), ('principal_amount', 0)), _connector='OR'), name='expense_split_matches_total_or_zero'),
        ),
    ]
