# Generated by Django 5.2.12 on 2026-03-06 08:27

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit_cards', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('merchant', models.CharField(blank=True, max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cash_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('repayment_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('principal_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fee_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('installment_count', models.PositiveIntegerField()),
                ('first_installment_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=24)),
                ('note', models.TextField(blank=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_purchases', to='finance.category')),
                ('linked_credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_purchases', to='credit_cards.creditcardaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-first_installment_date'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_on', models.DateField()),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('principal_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fee_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('installment_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='installments.installmentpurchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='installmentpurchase',
            index=models.Index(fields=['user', 'status', 'first_installment_date'], name='installment_user_id_6390bb_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentpurchaseitem',
            index=models.Index(fields=['user', 'due_on', 'status'], name='installment_user_id_80ff71_idx'),
        ),
        migrations.AddConstraint(
            model_name='installmentpurchaseitem',
            constraint=models.UniqueConstraint(fields=('installment_purchase', 'installment_number'), name='uniq_purchase_installment_number'),
        ),
    ]
